# Generated by Django 4.2 on 2024-05-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_cart_total_after_coupon_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='79F97A72', max_length=8),
        ),
    ]
